### ISSUE TITLE
Compilation instructions for one example platform

### ISSUE THREAD

**Issue by dfsp-spirit** [larc/gproshan#11]
Suggestion: Could you add example commands to install the dependencies and get the binary compiled for a single example platform (e.g., some Ubuntu LTS version)? Just something like:

_"Under Ubuntu 18.04, you could install the required dependencies with: apt-get install ..."._

I would really like to give gproshan a try for our research, but I am not an expert in building C/C++ applications and I spend hours trying to compile it and have not succeeded yet. I tried different Linux versions, but there always seems to be some library or compiler version wrong, a dependency missing, or whatever.

**Comment by larc** [comment]
We will add some guides to install the dependencies.
You can install them with `sudo apt-get install libarmadillo-dev libeigen3-dev libopenblas-dev libsuitesparse-dev freeglut3-dev libgles2-mesa-dev cimg-dev libcgal-dev` it must work.
The current code need cuda >= 10.1 and g++ >= 8, if not you can get some errors.

**Comment by larc** [comment]
Readme updated.

**Comment by dfsp-spirit** [comment]
Thanks a lot, it worked fine after that under Ubuntu 19.04.

(On a fresh install, one will have to add _build-essential_ and _cmake_ to the list of dependencies, but that's quite obvious and not the hard part. Just to let others who may come here know.)
