### ISSUE TITLE
Recomputing topleset for mesh with new source?

### ISSUE THREAD

**Issue by dfsp-spirit** [larc/gproshan#13]
I am trying to compute geodesic distance for all *n* source vertices in a mesh. How can I avoid reloading the mesh from disk *n* times?

This is for one source vert, and it works great:
```
 che * mesh;
 mesh = new che_off(my_mesh_file);  // load mesh from disk

 size_t n_vertices = mesh->n_vertices();
 vector <index_t> source = { 0 };
 index_t * toplesets = new index_t[n_vertices];
 index_t * sorted_index = new index_t[n_vertices];
 vector<index_t> limits;
mesh->compute_toplesets(toplesets, sorted_index, limits, source);
```

However, for the next source vert (in a loop), the call to `mesh->compute_toplesets` segfaults unless I reload the mesh in the loop:
```
vector <index_t> source = { loop_index };
...
 // mesh = new che_off(my_mesh_file);     // reaload mesh -- without this line it segfaults
 mesh->compute_toplesets(toplesets, sorted_index, limits, source);
```

How can I avoid reloading the mesh each time? Does is have a member function that will reset the state of the instance so I can call `compute_toplesets` again without reloading the mesh?

**Comment by dfsp-spirit** [comment]
Nevermind, it was my fault.

**Comment by larc** [comment]
Don't worry. Thanks.
